#:kivy 1.10.0
#:import FadeTransition kivy.uix.screenmanager.FadeTransition

Manager:
	transition: FadeTransition
	TelaInicial:
	Tela1:

<TelaInicial>:
	name: 'telainic'
	BoxLayout:
		orientation: 'vertical'
		Button:
			on_release: app.root.current = "selecVoo"
			text: "Voos"
			font_size: 50
			size_hint: (0.9, 0.9)

		Button:
			on_release: app.root.on_stop
			text: 'Sair'
			size_hint: (0.9, 0.9)
	
<Tela1>:
	name: 'selecVoo'